### ISSUE TITLE
Determine "rules of duplication" logic

### ISSUE THREAD

**Issue by AndrewSpittlemeister** [AndrewSpittlemeister/c4g-efsp-front-end#13]
An issue to discuss how duplication of funding requests will be determined.

**Comment by bryanbxian** [comment]
I think the "must have" requirement is what Charles currently uses: filtering out by full name and DOB

I like the idea of additional duplication checks, but I think it is a "nice to have" and that we should be careful before committing to this
- Our proposed changes may have deeper ethical ramifications. Additional duplication checks would change Charles' workflow, and what if the new workflow has negative effects? For example, what if 2 people truly had the same birthday and very similar names (off by a few letters maybe) and one was denied because of our feature? 
- It introduces feature creep, which requires more resources to develop, maintain, and change
